### ISSUE TITLE
Implementation registration for software Sustainability Tracker

### ISSUE THREAD

**Issue by remi-sustainablechoice** [uncefact/spec-untp#194]
# General Information 

### Organisation data

Organisation name : Sustainable Choice Group
Organisation homepage URL : https://www.sustainabilitytracker.com

Logo
![Logo](https://github.com/user-attachments/assets/837d4bf0-6f0d-46e9-a347-6b151aa3a42f)

Registration country : Australia
Operating countries : ("global")

### Implementation statement

Sustainability Tracker is a world first solution that houses brand sustainability credentials, initiatives, actions, and evidence in the palm of your hands.

By simplifying complex data, Sustainability Tracker helps consumers to make considered choices in real time while they shop and helps brands share their sustainability messages without greenwashing. We host the sustainability data of brands and businesses around the world, and fully intend to support Digital Product Passport development.

### Implementation Status

- [ X ] Registration of commitment to implement 
- [ ] Registration of tested implementation (attach test evidence)

### Implementation Scope

Select the UNTP specification items that you plan to implement / have implemented

- [ X ] Digital Product Passport
- [ ] Digital Facility Record
- [ ] Digital Traceability Event
- [ ] Digital Conformity Credential
- [ X ] Digital Identity Resolver
- [ ] Decentralised Access Control
- [ ] Sustainability Vocabulary Profile

Select the UNTP specification version(s) that you plan to support

- [ X ] Pre-release pilot versions 0.x.x
- [ X ] Stable first release version 1.x.x

# Role Specific Information 

### For Software Solutions

Please list your software products and major versions that you wish to register for UNTP implementation

Product name: Sustainability Tracker
Product URL: https://www.sustainabilitytracker.com

**Comment by onthebreeze** [comment]
Thank you for your commitment.  We expect to review and publish at the next UNTP meeting on friday 15th Nov.

**Comment by onthebreeze** [comment]
Registration is recorded in PR #210 - should be merged soon.

**Comment by onthebreeze** [comment]
thank you for your commitment - your entry is live at https://uncefact.github.io/spec-untp/docs/implementations/Software#sustainable-choice-group 

Please re-open this ticket to request corrections or update status.
